// projects/04-task-manager-svelte/src/lib/components/ToastContainer.svelte
<script lang="ts">
  import { taskStore } from '$lib/state/taskStore.svelte';
  import { CheckCircle2, AlertTriangle, Info, XCircle, X } from 'lucide-svelte';

  const icons = {
    success: CheckCircle2,
    info: Info,
    warning: AlertTriangle,
    error: XCircle
  };

  const styles = {
    success: 'bg-emerald-950/90 text-emerald-200 border-emerald-800/80',
    info: 'bg-indigo-950/90 text-indigo-200 border-indigo-800/80',
    warning: 'bg-amber-950/90 text-amber-200 border-amber-800/80',
    error: 'bg-rose-950/90 text-rose-200 border-rose-800/80'
  };
</script>

<div class="fixed bottom-4 right-4 z-50 flex flex-col gap-2 max-w-sm pointer-events-none">
  {#each taskStore.toasts as toast (toast.id)}
    {@const Icon = icons[toast.type] || Info}
    <div
      class="pointer-events-auto flex items-center justify-between gap-3 px-4 py-3 rounded-xl border backdrop-blur-md shadow-xl text-xs font-semibold animate-fade-in {styles[toast.type]}"
    >
      <div class="flex items-center gap-2">
        <Icon class="w-4 h-4 shrink-0" />
        <span>{toast.message}</span>
      </div>
      <button
        onclick={() => taskStore.removeToast(toast.id)}
        class="p-0.5 rounded opacity-70 hover:opacity-100 transition-opacity"
      >
        <X class="w-3.5 h-3.5" />
      </button>
    </div>
  {/each}
</div>

// projects/02-task-manager-nextjs/src/components/common/ToastContainer.tsx
"use client";

import React from "react";
import { CheckCircle2, AlertTriangle, Info, AlertOctagon, X } from "lucide-react";
import { useTaskStore } from "@/store/useTaskStore";

export function ToastContainer() {
  const { toasts, removeToast } = useTaskStore();

  if (toasts.length === 0) return null;

  return (
    <div className="fixed bottom-4 right-4 z-50 flex flex-col gap-2 max-w-sm pointer-events-none">
      {toasts.map((toast) => {
        let icon = <Info className="w-4 h-4 text-blue-500" />;
        let borderClass = "border-blue-500/30 bg-blue-50/90 dark:bg-slate-900/95";

        if (toast.type === "success") {
          icon = <CheckCircle2 className="w-4 h-4 text-emerald-500" />;
          borderClass = "border-emerald-500/30 bg-emerald-50/90 dark:bg-slate-900/95";
        } else if (toast.type === "warning") {
          icon = <AlertTriangle className="w-4 h-4 text-amber-500" />;
          borderClass = "border-amber-500/30 bg-amber-50/90 dark:bg-slate-900/95";
        } else if (toast.type === "error") {
          icon = <AlertOctagon className="w-4 h-4 text-rose-500" />;
          borderClass = "border-rose-500/30 bg-rose-50/90 dark:bg-slate-900/95";
        }

        return (
          <div
            key={toast.id}
            className={`pointer-events-auto flex items-center justify-between gap-3 px-4 py-3 rounded-xl border shadow-lg backdrop-blur-md animate-fade-in-scale text-xs font-semibold ${borderClass}`}
          >
            <div className="flex items-center gap-2">
              {icon}
              <span className="text-slate-900 dark:text-slate-100">{toast.text}</span>
            </div>
            <button
              onClick={() => removeToast(toast.id)}
              className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-200"
            >
              <X className="w-3.5 h-3.5" />
            </button>
          </div>
        );
      })}
    </div>
  );
}
