// projects/02-task-manager-nextjs/src/app/tasks/[id]/page.tsx
"use client";

import React, { use } from "react";
import Link from "next/link";
import {
  ArrowLeft,
  Calendar,
  Clock,
  Tag,
  CheckCircle2,
  CircleAlert,
  Edit2,
  Trash2,
  CheckSquare,
  Square,
  History,
  Layers,
} from "lucide-react";
import { useTaskStore } from "@/store/useTaskStore";
import type { TaskPriority, TaskStatus } from "@/types/task";

export default function TaskDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = use(params);
  const { tasks, updateTaskStatus, toggleSubtask, deleteTask, openEditModal } = useTaskStore();

  const task = tasks.find((t) => t.id === id);

  if (!task) {
    return (
      <div className="min-h-[50vh] flex flex-col items-center justify-center text-center p-6 space-y-4">
        <CircleAlert className="w-12 h-12 text-rose-500" />
        <h2 className="text-xl font-bold">Task Not Found</h2>
        <p className="text-xs text-slate-500">The task ID "{id}" could not be located in store.</p>
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 px-4 py-2 bg-indigo-600 text-white text-xs font-bold rounded-xl shadow-md"
        >
          <ArrowLeft className="w-4 h-4" /> Return to Board
        </Link>
      </div>
    );
  }

  const getPriorityBadge = (priority: TaskPriority) => {
    switch (priority) {
      case "urgent":
        return <span className="px-2.5 py-1 rounded-full text-xs font-extrabold bg-rose-500/10 text-rose-600 dark:text-rose-400 border border-rose-500/20">URGENT PRIORITY</span>;
      case "high":
        return <span className="px-2.5 py-1 rounded-full text-xs font-extrabold bg-amber-500/10 text-amber-600 dark:text-amber-400 border border-amber-500/20">HIGH PRIORITY</span>;
      case "medium":
        return <span className="px-2.5 py-1 rounded-full text-xs font-extrabold bg-sky-500/10 text-sky-600 dark:text-sky-400 border border-sky-500/20">MEDIUM PRIORITY</span>;
      case "low":
      default:
        return <span className="px-2.5 py-1 rounded-full text-xs font-extrabold bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20">LOW PRIORITY</span>;
    }
  };

  const getStatusPill = (status: TaskStatus) => {
    switch (status) {
      case "completed":
        return (
          <span className="inline-flex items-center gap-1 px-3 py-1 rounded-full text-xs font-extrabold bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border border-emerald-500/20">
            <CheckCircle2 className="w-3.5 h-3.5 text-emerald-500" /> Completed
          </span>
        );
      case "in_progress":
        return (
          <span className="inline-flex items-center gap-1 px-3 py-1 rounded-full text-xs font-extrabold bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border border-indigo-500/20">
            <Clock className="w-3.5 h-3.5 text-indigo-500" /> In Progress
          </span>
        );
      case "todo":
      default:
        return (
          <span className="inline-flex items-center gap-1 px-3 py-1 rounded-full text-xs font-extrabold bg-amber-500/10 text-amber-600 dark:text-amber-400 border border-amber-500/20">
            <CircleAlert className="w-3.5 h-3.5 text-amber-500" /> To Do
          </span>
        );
    }
  };

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      {/* Breadcrumb Back Link */}
      <Link
        href="/"
        className="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-500 hover:text-slate-900 dark:hover:text-slate-100 transition-colors"
      >
        <ArrowLeft className="w-4 h-4" /> Back to Previous Page
      </Link>

      {/* Main Task Detail Card */}
      <div className="bg-white/90 dark:bg-slate-900/90 border border-slate-200/80 dark:border-slate-800/80 rounded-2xl p-6 shadow-sm backdrop-blur-sm space-y-6">
        {/* Header Title & Category */}
        <div className="flex flex-col sm:flex-row sm:items-start justify-between gap-4 border-b border-slate-200/80 dark:border-slate-800/80 pb-5">
          <div className="space-y-2">
            <div className="flex items-center gap-2">
              <span className="text-xs font-bold text-indigo-600 dark:text-indigo-400 bg-indigo-50 dark:bg-indigo-950/60 px-2.5 py-1 rounded-lg border border-indigo-200/50 dark:border-indigo-800/50">
                {task.category || "General"}
              </span>
              {getStatusPill(task.status)}
            </div>
            <h1 className="text-2xl font-extrabold tracking-tight text-slate-900 dark:text-slate-100">
              {task.title}
            </h1>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => openEditModal(task)}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-xs font-bold rounded-xl transition-colors"
            >
              <Edit2 className="w-3.5 h-3.5" /> Edit
            </button>
            <button
              onClick={() => deleteTask(task.id)}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-rose-500/10 hover:bg-rose-500/20 text-rose-600 dark:text-rose-400 text-xs font-bold rounded-xl border border-rose-500/30 transition-colors"
            >
              <Trash2 className="w-3.5 h-3.5" /> Delete
            </button>
          </div>
        </div>

        {/* Description Box */}
        <div className="bg-slate-50/80 dark:bg-slate-950/60 p-5 rounded-xl border border-slate-200/60 dark:border-slate-800/60">
          <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-2">
            Description
          </h3>
          <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed whitespace-pre-line">
            {task.description || "No description provided."}
          </p>
        </div>

        {/* Metadata Grid (3 Cards) */}
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          <div className="p-4 bg-slate-50/80 dark:bg-slate-950/60 rounded-xl border border-slate-200/60 dark:border-slate-800/60 space-y-1">
            <span className="text-[10px] font-bold uppercase text-slate-400">Priority Level</span>
            <div>{getPriorityBadge(task.priority)}</div>
          </div>

          <div className="p-4 bg-slate-50/80 dark:bg-slate-950/60 rounded-xl border border-slate-200/60 dark:border-slate-800/60 space-y-1">
            <span className="text-[10px] font-bold uppercase text-slate-400">Target Due Date</span>
            <div className="flex items-center gap-1.5 font-mono text-xs font-bold text-slate-800 dark:text-slate-200">
              <Calendar className="w-3.5 h-3.5 text-indigo-500" />
              {task.dueDate || "Not set"}
            </div>
          </div>

          <div className="p-4 bg-slate-50/80 dark:bg-slate-950/60 rounded-xl border border-slate-200/60 dark:border-slate-800/60 space-y-1">
            <span className="text-[10px] font-bold uppercase text-slate-400">Created Date</span>
            <div className="flex items-center gap-1.5 font-mono text-xs font-bold text-slate-800 dark:text-slate-200">
              <Clock className="w-3.5 h-3.5 text-indigo-500" />
              {new Date(task.createdAt).toLocaleDateString()}
            </div>
          </div>
        </div>

        {/* Tags Section */}
        {task.tags && task.tags.length > 0 && (
          <div className="space-y-2">
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
              Associated Tags
            </h3>
            <div className="flex flex-wrap gap-1.5">
              {task.tags.map((t) => (
                <span
                  key={t}
                  className="inline-flex items-center gap-1 text-xs font-semibold text-slate-700 dark:text-slate-300 bg-slate-100 dark:bg-slate-800 px-2.5 py-1 rounded-lg border border-slate-200/60 dark:border-slate-700/60"
                >
                  <Tag className="w-3 h-3 text-indigo-500" />#{t}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Sub-tasks Checklist */}
        {task.subtasks && task.subtasks.length > 0 && (
          <div className="space-y-3 pt-2">
            <div className="flex items-center justify-between">
              <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">
                Sub-tasks Checklist ({task.subtasks.filter((s) => s.completed).length}/{task.subtasks.length})
              </h3>
            </div>
            <div className="space-y-2">
              {task.subtasks.map((st) => (
                <button
                  key={st.id}
                  onClick={() => toggleSubtask(task.id, st.id)}
                  className="w-full flex items-center gap-3 p-3 bg-slate-50 dark:bg-slate-950 rounded-xl border border-slate-200/60 dark:border-slate-800/60 text-left hover:border-indigo-500/40 transition-colors"
                >
                  {st.completed ? (
                    <CheckSquare className="w-4 h-4 text-emerald-500 shrink-0" />
                  ) : (
                    <Square className="w-4 h-4 text-slate-400 shrink-0" />
                  )}
                  <span
                    className={`text-xs font-medium ${
                      st.completed ? "line-through text-slate-400" : "text-slate-800 dark:text-slate-200"
                    }`}
                  >
                    {st.title}
                  </span>
                </button>
              ))}
            </div>
          </div>
        )}

        {/* Activity Timestamp Log */}
        {task.history && task.history.length > 0 && (
          <div className="space-y-3 pt-2 border-t border-slate-200/80 dark:border-slate-800/80">
            <h3 className="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400 flex items-center gap-1.5">
              <History className="w-3.5 h-3.5 text-indigo-500" /> Activity History Log
            </h3>
            <div className="space-y-2 max-h-40 overflow-y-auto">
              {task.history.map((log) => (
                <div
                  key={log.id}
                  className="flex items-center justify-between text-xs py-1.5 px-3 bg-slate-50/50 dark:bg-slate-950/50 rounded-lg text-slate-600 dark:text-slate-400"
                >
                  <span>{log.text}</span>
                  <span className="font-mono text-[10px] text-slate-400">
                    {new Date(log.timestamp).toLocaleTimeString()}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Quick Status Switcher */}
        <div className="pt-4 border-t border-slate-200/80 dark:border-slate-800/80 flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <span className="text-xs font-bold text-slate-600 dark:text-slate-400 flex items-center gap-1.5">
            <Layers className="w-4 h-4 text-indigo-500" /> Quick Status Switcher:
          </span>

          <div className="flex items-center gap-2">
            <button
              onClick={() => updateTaskStatus(task.id, "todo")}
              className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all ${
                task.status === "todo"
                  ? "bg-amber-500 text-white shadow-sm"
                  : "bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 hover:bg-slate-200"
              }`}
            >
              To Do
            </button>
            <button
              onClick={() => updateTaskStatus(task.id, "in_progress")}
              className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all ${
                task.status === "in_progress"
                  ? "bg-indigo-600 text-white shadow-sm"
                  : "bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 hover:bg-slate-200"
              }`}
            >
              In Progress
            </button>
            <button
              onClick={() => updateTaskStatus(task.id, "completed")}
              className={`px-3 py-1.5 rounded-xl text-xs font-bold transition-all ${
                task.status === "completed"
                  ? "bg-emerald-600 text-white shadow-sm"
                  : "bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400 hover:bg-slate-200"
              }`}
            >
              Completed
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}

// projects/04-task-manager-svelte/src/routes/tasks/[id]/+page.svelte
<script lang="ts">
  import { taskStore } from '$lib/state/taskStore.svelte';
  import type { PageData } from './$types';
  import {
    ArrowLeft,
    Calendar,
    Tag,
    Edit3,
    Trash2,
    CheckCircle2,
    Clock,
    CircleAlert
  } from 'lucide-svelte';

  let { data }: { data: PageData } = $props();

  let task = $derived(
    taskStore.tasks.find((t) => t.id === data.taskId) || data.fallbackTask
  );

  const priorityBadgeStyles: Record<string, string> = {
    low: 'text-emerald-600 dark:text-emerald-300 bg-emerald-500/10 border-emerald-500/30',
    medium: 'text-sky-600 dark:text-sky-300 bg-sky-500/10 border-sky-500/30',
    high: 'text-amber-600 dark:text-amber-300 bg-amber-500/10 border-amber-500/30',
    urgent: 'text-rose-600 dark:text-rose-300 bg-rose-500/10 border-rose-500/30'
  };

  const statusBadges: Record<string, { label: string; style: string; icon: any }> = {
    todo: { label: 'To Do', style: 'text-amber-500 bg-amber-500/10 border-amber-500/30', icon: CircleAlert },
    in_progress: { label: 'In Progress', style: 'text-indigo-500 bg-indigo-500/10 border-indigo-500/30', icon: Clock },
    completed: { label: 'Completed', style: 'text-emerald-500 bg-emerald-500/10 border-emerald-500/30', icon: CheckCircle2 }
  };
</script>

<svelte:head>
  <title>{task ? task.title : 'Task Details'} — TaskFlow</title>
  <meta name="description" content={task ? task.description : 'Task details page'} />
</svelte:head>

<div class="max-w-4xl mx-auto space-y-6">
  
  {#if task}
    {@const statusInfo = statusBadges[task.status] || statusBadges.todo}
    {@const StatusIcon = statusInfo.icon}

    <!-- Main Detail Glass Panel -->
    <div class="glass-panel p-8 rounded-2xl border border-slate-200/80 dark:border-slate-800/80 space-y-6 shadow-md">
      
      <!-- Top Back Link -->
      <div>
        <a
          href="/tasks"
          class="inline-flex items-center gap-1.5 text-xs font-semibold text-slate-400 hover:text-slate-200 transition-colors"
        >
          <ArrowLeft class="w-3.5 h-3.5" />
          <span>Back to Previous Page</span>
        </a>
      </div>

      <!-- Title & Category Header -->
      <div class="flex items-start justify-between gap-4 border-b border-slate-200/80 dark:border-slate-800/80 pb-6">
        <div class="space-y-1">
          {#if task.category}
            <span class="text-xs font-extrabold text-indigo-500 uppercase tracking-wider block">
              {task.category}
            </span>
          {/if}
          <h1 class="text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-white tracking-tight">
            {task.title}
          </h1>
        </div>

        <span class="inline-flex items-center gap-1.5 px-3 py-1 rounded-full border text-xs font-bold uppercase shrink-0 {statusInfo.style}">
          <StatusIcon class="w-3.5 h-3.5" />
          <span>{statusInfo.label}</span>
        </span>
      </div>

      <!-- Task Description Section -->
      <div class="space-y-2">
        <h3 class="text-[11px] font-extrabold text-slate-400 uppercase tracking-wider">TASK DESCRIPTION</h3>
        <div class="p-5 rounded-xl bg-slate-100/70 dark:bg-[#070a13]/80 border border-slate-200/80 dark:border-slate-800/80 text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
          {task.description || 'No detailed description provided.'}
        </div>
      </div>

      <!-- Metadata Grid (3 Cards) -->
      <div class="grid grid-cols-1 sm:grid-cols-3 gap-4 pt-2">
        <div class="p-4 rounded-xl bg-slate-100/60 dark:bg-[#070a13]/60 border border-slate-200/80 dark:border-slate-800/80 space-y-1.5">
          <span class="text-[11px] font-semibold text-slate-400 block">Priority Level</span>
          <span class="inline-block text-[10px] font-extrabold uppercase tracking-wider px-2.5 py-0.5 rounded-md border {priorityBadgeStyles[task.priority] || priorityBadgeStyles.low}">
            {task.priority}
          </span>
        </div>

        <div class="p-4 rounded-xl bg-slate-100/60 dark:bg-[#070a13]/60 border border-slate-200/80 dark:border-slate-800/80 space-y-1.5">
          <span class="text-[11px] font-semibold text-slate-400 block">Target Due Date</span>
          <div class="flex items-center gap-1.5 text-xs font-mono font-bold text-slate-900 dark:text-white">
            <Calendar class="w-3.5 h-3.5 text-indigo-500" />
            <span>{task.dueDate || 'No due date'}</span>
          </div>
        </div>

        <div class="p-4 rounded-xl bg-slate-100/60 dark:bg-[#070a13]/60 border border-slate-200/80 dark:border-slate-800/80 space-y-1.5">
          <span class="text-[11px] font-semibold text-slate-400 block">Created On</span>
          <span class="text-xs font-mono font-bold text-slate-900 dark:text-white block">
            {new Date(task.createdAt).toLocaleDateString()}
          </span>
        </div>
      </div>

      <!-- Associated Tags Section -->
      {#if task.tags && task.tags.length > 0}
        <div class="space-y-2 pt-2">
          <h3 class="text-[11px] font-extrabold text-slate-400 uppercase tracking-wider">ASSOCIATED TAGS</h3>
          <div class="flex flex-wrap gap-2">
            {#each task.tags as tag}
              <span class="inline-flex items-center gap-1 px-3 py-1 rounded-xl bg-slate-200/80 dark:bg-slate-800/80 border border-slate-300/80 dark:border-slate-700/80 text-indigo-600 dark:text-indigo-300 text-xs font-bold">
                <Tag class="w-3 h-3" />
                #{tag}
              </span>
            {/each}
          </div>
        </div>
      {/if}

      <!-- Bottom Actions & Quick Status Switcher -->
      <div class="pt-6 border-t border-slate-200/80 dark:border-slate-800/80 flex flex-wrap items-center justify-between gap-4">
        <div class="flex items-center gap-2">
          <button
            onclick={() => taskStore.openModal(task.id)}
            class="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-indigo-600 text-white text-xs font-bold shadow-md shadow-indigo-500/20 active:scale-95 transition-all"
          >
            <Edit3 class="w-3.5 h-3.5" />
            <span>Edit Task</span>
          </button>

          <button
            onclick={() => {
              taskStore.deleteTask(task.id);
              window.location.href = '/tasks';
            }}
            class="flex items-center gap-1.5 px-3.5 py-2 rounded-xl bg-rose-500/10 text-rose-500 border border-rose-500/20 text-xs font-bold hover:bg-rose-500/20 transition-all"
          >
            <Trash2 class="w-3.5 h-3.5" />
            <span>Delete</span>
          </button>
        </div>

        <div class="flex items-center gap-2">
          <span class="text-xs font-semibold text-slate-400 mr-1">Quick Status Switch:</span>
          <button
            onclick={() => taskStore.updateStatus(task.id, 'todo')}
            class="px-3 py-1.5 rounded-lg text-xs font-bold border transition-all {task.status === 'todo' ? 'bg-amber-500 text-white border-amber-500 shadow-md' : 'bg-slate-100 dark:bg-slate-800/80 text-slate-400 border-slate-300 dark:border-slate-700 hover:text-white'}"
          >
            To Do
          </button>
          <button
            onclick={() => taskStore.updateStatus(task.id, 'in_progress')}
            class="px-3 py-1.5 rounded-lg text-xs font-bold border transition-all {task.status === 'in_progress' ? 'bg-indigo-600 text-white border-indigo-600 shadow-md' : 'bg-slate-100 dark:bg-slate-800/80 text-slate-400 border-slate-300 dark:border-slate-700 hover:text-white'}"
          >
            In Progress
          </button>
          <button
            onclick={() => taskStore.updateStatus(task.id, 'completed')}
            class="px-3 py-1.5 rounded-lg text-xs font-bold border transition-all {task.status === 'completed' ? 'bg-emerald-600 text-white border-emerald-600 shadow-md' : 'bg-slate-100 dark:bg-slate-800/80 text-slate-400 border-slate-300 dark:border-slate-700 hover:text-white'}"
          >
            Completed
          </button>
        </div>
      </div>

    </div>
  {:else}
    <div class="text-center py-16 text-slate-400">
      <p class="text-base font-bold">Task Not Found</p>
      <a href="/tasks" class="text-xs text-indigo-500 hover:underline mt-2 inline-block">Back to Task List</a>
    </div>
  {/if}

</div>
