// projects/02-task-manager-nextjs/src/components/common/TaskFormModal.tsx
"use client";

import React, { useEffect, useState } from "react";
import { X, Plus, Trash2, Tag, Calendar, Layers, Flag } from "lucide-react";
import { useTaskStore } from "@/store/useTaskStore";
import type { TaskPriority, TaskStatus, SubTask } from "@/types/task";

export function TaskFormModal() {
  const { isModalOpen, editingTask, closeModal, addTask, updateTask } = useTaskStore();

  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [status, setStatus] = useState<TaskStatus>("todo");
  const [priority, setPriority] = useState<TaskPriority>("medium");
  const [category, setCategory] = useState("Frontend");
  const [dueDate, setDueDate] = useState("");
  const [tagsInput, setTagsInput] = useState("");
  const [subtasks, setSubtasks] = useState<SubTask[]>([]);
  const [newSubtaskTitle, setNewSubtaskTitle] = useState("");

  useEffect(() => {
    if (editingTask) {
      setTitle(editingTask.title);
      setDescription(editingTask.description);
      setStatus(editingTask.status);
      setPriority(editingTask.priority);
      setCategory(editingTask.category);
      setDueDate(editingTask.dueDate);
      setTagsInput(editingTask.tags ? editingTask.tags.join(", ") : "");
      setSubtasks(editingTask.subtasks || []);
    } else {
      setTitle("");
      setDescription("");
      setStatus("todo");
      setPriority("medium");
      setCategory("Frontend");
      setDueDate(new Date().toISOString().split("T")[0]);
      setTagsInput("Next.js, React");
      setSubtasks([]);
    }
  }, [editingTask, isModalOpen]);

  if (!isModalOpen) return null;

  const handleAddSubtask = () => {
    if (!newSubtaskTitle.trim()) return;
    setSubtasks((prev) => [
      ...prev,
      { id: `sub-${crypto.randomUUID()}`, title: newSubtaskTitle.trim(), completed: false },
    ]);
    setNewSubtaskTitle("");
  };

  const handleRemoveSubtask = (id: string) => {
    setSubtasks((prev) => prev.filter((s) => s.id !== id));
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim()) return;

    const tags = tagsInput
      .split(",")
      .map((t) => t.trim())
      .filter((t) => t.length > 0);

    if (editingTask) {
      updateTask(editingTask.id, {
        title: title.trim(),
        description: description.trim(),
        status,
        priority,
        category: category.trim() || "General",
        dueDate,
        tags,
        subtasks,
      });
    } else {
      addTask({
        title: title.trim(),
        description: description.trim(),
        status,
        priority,
        category: category.trim() || "General",
        dueDate: dueDate || new Date().toISOString().split("T")[0],
        tags,
        subtasks,
      });
    }
    closeModal();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm">
      <div className="bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 rounded-2xl shadow-2xl w-full max-w-lg overflow-hidden animate-fade-in-scale flex flex-col max-h-[85vh]">
        {/* Fixed Header */}
        <div className="px-6 py-4 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between shrink-0 bg-slate-50/50 dark:bg-slate-950/50">
          <h3 className="text-base font-bold text-slate-900 dark:text-slate-100">
            {editingTask ? "Edit Task" : "Create New Task"}
          </h3>
          <button
            onClick={closeModal}
            aria-label="Close modal"
            className="p-1 rounded-lg text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 hover:bg-slate-200/50 dark:hover:bg-slate-800/50 transition-colors"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Scrollable Form Body */}
        <form id="task-form" onSubmit={handleSubmit} className="p-6 space-y-4 overflow-y-auto shrink grow">
          {/* Title Input */}
          <div>
            <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">
              Task Title <span className="text-rose-500">*</span>
            </label>
            <input
              type="text"
              required
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g. Implement Next.js App Router Architecture"
              className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-xl text-xs focus:outline-none focus:ring-2 focus:ring-indigo-500/50 font-medium"
            />
          </div>

          {/* Description */}
          <div>
            <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">Description</label>
            <textarea
              rows={3}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Detailed description of task objectives and scope..."
              className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-xl text-xs focus:outline-none focus:ring-2 focus:ring-indigo-500/50 font-normal resize-none"
            />
          </div>

          {/* Status & Priority Grid */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1 flex items-center gap-1">
                <Layers className="w-3.5 h-3.5 text-indigo-500" /> Status
              </label>
              <select
                value={status}
                onChange={(e) => setStatus(e.target.value as TaskStatus)}
                aria-label="Select task status"
                className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-xl text-xs font-medium focus:outline-none focus:ring-2 focus:ring-indigo-500/50 cursor-pointer"
              >
                <option value="todo">To Do</option>
                <option value="in_progress">In Progress</option>
                <option value="completed">Completed</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1 flex items-center gap-1">
                <Flag className="w-3.5 h-3.5 text-amber-500" /> Priority
              </label>
              <select
                value={priority}
                onChange={(e) => setPriority(e.target.value as TaskPriority)}
                aria-label="Select task priority"
                className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-xl text-xs font-medium focus:outline-none focus:ring-2 focus:ring-indigo-500/50 cursor-pointer"
              >
                <option value="low">Low Priority</option>
                <option value="medium">Medium Priority</option>
                <option value="high">High Priority</option>
                <option value="urgent">Urgent Priority</option>
              </select>
            </div>
          </div>

          {/* Category & Due Date */}
          <div className="grid grid-cols-2 gap-3">
            <div>
              <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1">Category</label>
              <input
                type="text"
                value={category}
                onChange={(e) => setCategory(e.target.value)}
                placeholder="e.g. Frontend, API"
                className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-xl text-xs focus:outline-none focus:ring-2 focus:ring-indigo-500/50"
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1 flex items-center gap-1">
                <Calendar className="w-3.5 h-3.5 text-slate-400" /> Due Date
              </label>
              <input
                type="date"
                value={dueDate}
                onChange={(e) => setDueDate(e.target.value)}
                className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-xl text-xs focus:outline-none focus:ring-2 focus:ring-indigo-500/50"
              />
            </div>
          </div>

          {/* Tags Input */}
          <div>
            <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1 flex items-center gap-1">
              <Tag className="w-3.5 h-3.5 text-indigo-500" /> Tags (comma separated)
            </label>
            <input
              type="text"
              value={tagsInput}
              onChange={(e) => setTagsInput(e.target.value)}
              placeholder="Next.js, App Router, SSR"
              className="w-full px-3 py-2 bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-xl text-xs focus:outline-none focus:ring-2 focus:ring-indigo-500/50"
            />
          </div>

          {/* Subtasks Checklist Creator */}
          <div>
            <label className="block text-xs font-bold text-slate-700 dark:text-slate-300 mb-1.5">
              Sub-tasks / Checklist ({subtasks.length})
            </label>
            <div className="flex gap-2 mb-2">
              <input
                type="text"
                value={newSubtaskTitle}
                onChange={(e) => setNewSubtaskTitle(e.target.value)}
                placeholder="Add sub-task item..."
                onKeyDown={(e) => {
                  if (e.key === "Enter") {
                    e.preventDefault();
                    handleAddSubtask();
                  }
                }}
                className="flex-1 px-3 py-1.5 bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-xl text-xs"
              />
              <button
                type="button"
                onClick={handleAddSubtask}
                className="px-3 py-1.5 bg-slate-200 dark:bg-slate-800 hover:bg-slate-300 dark:hover:bg-slate-700 text-xs font-bold rounded-xl transition-colors"
              >
                <Plus className="w-3.5 h-3.5" />
              </button>
            </div>

            {subtasks.length > 0 && (
              <div className="space-y-1.5 max-h-32 overflow-y-auto p-2 bg-slate-50 dark:bg-slate-950 rounded-xl border border-slate-200 dark:border-slate-800">
                {subtasks.map((s) => (
                  <div key={s.id} className="flex items-center justify-between gap-2 text-xs py-1 px-2 bg-white dark:bg-slate-900 rounded-lg border border-slate-200/60 dark:border-slate-800/60">
                    <span className="truncate">{s.title}</span>
                    <button
                      type="button"
                      onClick={() => handleRemoveSubtask(s.id)}
                      className="text-rose-500 hover:text-rose-700"
                    >
                      <Trash2 className="w-3 h-3" />
                    </button>
                  </div>
                ))}
              </div>
            )}
          </div>
        </form>

        {/* Fixed Action Footer */}
        <div className="px-6 py-3 border-t border-slate-200 dark:border-slate-800 flex items-center justify-end gap-2 shrink-0 bg-slate-50/50 dark:bg-slate-950/50">
          <button
            type="button"
            onClick={closeModal}
            className="px-4 py-2 text-xs font-semibold text-slate-600 dark:text-slate-400 hover:bg-slate-200/60 dark:hover:bg-slate-800/60 rounded-xl transition-colors"
          >
            Cancel
          </button>
          <button
            type="submit"
            form="task-form"
            className="px-4 py-2 bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-500 hover:to-violet-500 text-white text-xs font-bold rounded-xl shadow-md shadow-indigo-500/20 active:scale-95 transition-all"
          >
            {editingTask ? "Save Changes" : "Create Task"}
          </button>
        </div>
      </div>
    </div>
  );
}

// projects/04-task-manager-svelte/src/lib/components/TaskFormModal.svelte
<script lang="ts">
  import { taskStore } from '$lib/state/taskStore.svelte';
  import type { TaskPriority, TaskStatus } from '$lib/types/task';
  import { X, Save } from 'lucide-svelte';

  let title = $state('');
  let description = $state('');
  let priority = $state<TaskPriority>('medium');
  let status = $state<TaskStatus>('todo');
  let category = $state('General');
  let dueDate = $state('');
  let tagInput = $state('');
  let tags = $state<string[]>([]);

  const optionClass = "bg-white text-slate-900 dark:bg-[#0d1322] dark:text-slate-100 py-1";

  $effect(() => {
    if (taskStore.isModalOpen) {
      if (taskStore.editingTaskId) {
        const existing = taskStore.tasks.find((t) => t.id === taskStore.editingTaskId);
        if (existing) {
          title = existing.title;
          description = existing.description;
          priority = existing.priority;
          status = existing.status;
          category = existing.category;
          dueDate = existing.dueDate;
          tags = [...existing.tags];
        }
      } else {
        // Reset defaults
        title = '';
        description = '';
        priority = 'medium';
        status = 'todo';
        category = 'General';
        dueDate = new Date().toISOString().split('T')[0];
        tagInput = '';
        tags = ['svelte', 'task'];
      }
    }
  });

  function handleSubmit(e: SubmitEvent) {
    e.preventDefault();
    if (!title.trim()) return;

    if (taskStore.editingTaskId) {
      taskStore.updateTask(taskStore.editingTaskId, {
        title,
        description,
        priority,
        status,
        category,
        dueDate,
        tags
      });
    } else {
      taskStore.addTask({
        title,
        description,
        priority,
        status,
        category,
        dueDate,
        tags
      });
    }

    taskStore.closeModal();
  }

  function addTag() {
    if (tagInput.trim() && !tags.includes(tagInput.trim().toLowerCase())) {
      tags = [...tags, tagInput.trim().toLowerCase()];
      tagInput = '';
    }
  }

  function removeTag(tag: string) {
    tags = tags.filter((t) => t !== tag);
  }
</script>

{#if taskStore.isModalOpen}
  <!-- Inset Fixed Screen Backdrop -->
  <div
    role="button"
    tabindex="-1"
    aria-label="Close modal backdrop"
    class="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-sm animate-fade-in"
    onclick={(e) => {
      if (e.target === e.currentTarget) taskStore.closeModal();
    }}
    onkeydown={(e) => {
      if (e.key === 'Escape' || e.key === 'Enter' || e.key === ' ') taskStore.closeModal();
    }}
  >
    <!-- Dialog Panel Container -->
    <div class="w-full max-w-lg bg-white dark:bg-[#0d1322] border border-slate-200 dark:border-slate-800 rounded-2xl shadow-2xl overflow-hidden flex flex-col max-h-[85vh]">
      
      <!-- Fixed Header (shrink-0) -->
      <div class="px-6 py-4 border-b border-slate-200 dark:border-slate-800 flex items-center justify-between shrink-0 bg-slate-50/50 dark:bg-[#070a13]/50">
        <h3 class="text-base font-extrabold text-slate-900 dark:text-slate-100 flex items-center gap-2">
          {taskStore.editingTaskId ? 'Edit Task' : 'Create New Task'}
        </h3>
        <button
          onclick={() => taskStore.closeModal()}
          class="p-1.5 rounded-lg text-slate-400 hover:text-slate-600 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
        >
          <X class="w-4 h-4" />
        </button>
      </div>

      <!-- Scrollable Form Body (overflow-y-auto) -->
      <form id="task-modal-form" onsubmit={handleSubmit} class="p-6 space-y-4 overflow-y-auto flex-1">
        
        <!-- Task Title -->
        <div class="space-y-1">
          <label for="task-title" class="text-xs font-bold text-slate-700 dark:text-slate-300">
            Task Title <span class="text-rose-500">*</span>
          </label>
          <input
            id="task-title"
            type="text"
            required
            bind:value={title}
            placeholder="e.g. Implement Svelte 5 Runes state store"
            class="w-full px-3.5 py-2 text-xs rounded-xl bg-slate-50 dark:bg-[#070a13] border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-slate-100 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-indigo-500/50"
          />
        </div>

        <!-- Description -->
        <div class="space-y-1">
          <label for="task-desc" class="text-xs font-bold text-slate-700 dark:text-slate-300">
            Description
          </label>
          <textarea
            id="task-desc"
            rows="3"
            bind:value={description}
            placeholder="Detailed description of task scope and deliverables..."
            class="w-full px-3.5 py-2 text-xs rounded-xl bg-slate-50 dark:bg-[#070a13] border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-slate-100 placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-indigo-500/50 resize-none"
          ></textarea>
        </div>

        <!-- Grid: Priority & Status -->
        <div class="grid grid-cols-2 gap-3">
          <div class="space-y-1">
            <label for="task-priority" class="text-xs font-bold text-slate-700 dark:text-slate-300">
              Priority
            </label>
            <select
              id="task-priority"
              bind:value={priority}
              class="w-full px-3 py-2 text-xs rounded-xl bg-slate-50 dark:bg-[#070a13] border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-slate-100 focus:outline-none focus:ring-2 focus:ring-indigo-500/50 cursor-pointer"
            >
              <option value="low" class={optionClass}>Low</option>
              <option value="medium" class={optionClass}>Medium</option>
              <option value="high" class={optionClass}>High</option>
              <option value="urgent" class={optionClass}>Urgent</option>
            </select>
          </div>

          <div class="space-y-1">
            <label for="task-status" class="text-xs font-bold text-slate-700 dark:text-slate-300">
              Status
            </label>
            <select
              id="task-status"
              bind:value={status}
              class="w-full px-3 py-2 text-xs rounded-xl bg-slate-50 dark:bg-[#070a13] border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-slate-100 focus:outline-none focus:ring-2 focus:ring-indigo-500/50 cursor-pointer"
            >
              <option value="todo" class={optionClass}>To Do</option>
              <option value="in_progress" class={optionClass}>In Progress</option>
              <option value="completed" class={optionClass}>Completed</option>
            </select>
          </div>
        </div>

        <!-- Grid: Category & Due Date -->
        <div class="grid grid-cols-2 gap-3">
          <div class="space-y-1">
            <label for="task-category" class="text-xs font-bold text-slate-700 dark:text-slate-300">
              Category
            </label>
            <input
              id="task-category"
              type="text"
              bind:value={category}
              placeholder="e.g. Frontend"
              class="w-full px-3.5 py-2 text-xs rounded-xl bg-slate-50 dark:bg-[#070a13] border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-slate-100 focus:outline-none focus:ring-2 focus:ring-indigo-500/50"
            />
          </div>

          <div class="space-y-1">
            <label for="task-duedate" class="text-xs font-bold text-slate-700 dark:text-slate-300">
              Due Date
            </label>
            <input
              id="task-duedate"
              type="date"
              bind:value={dueDate}
              class="w-full px-3.5 py-2 text-xs rounded-xl bg-slate-50 dark:bg-[#070a13] border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-slate-100 focus:outline-none focus:ring-2 focus:ring-indigo-500/50 cursor-pointer"
            />
          </div>
        </div>

        <!-- Tags Input Section -->
        <div class="space-y-2">
          <label for="task-tags" class="text-xs font-bold text-slate-700 dark:text-slate-300">
            Tags (#tag)
          </label>
          <div class="flex gap-2">
            <input
              id="task-tags"
              type="text"
              bind:value={tagInput}
              onkeydown={(e) => {
                if (e.key === 'Enter') {
                  e.preventDefault();
                  addTag();
                }
              }}
              placeholder="Type tag and press enter..."
              class="flex-1 px-3 py-1.5 text-xs rounded-xl bg-slate-50 dark:bg-[#070a13] border border-slate-200 dark:border-slate-800 text-slate-900 dark:text-slate-100"
            />
            <button
              type="button"
              onclick={addTag}
              class="px-3 py-1.5 text-xs font-semibold rounded-xl bg-slate-200 dark:bg-slate-800 text-slate-700 dark:text-slate-200 hover:bg-slate-300 dark:hover:bg-slate-700 transition-colors"
            >
              Add
            </button>
          </div>

          <div class="flex flex-wrap gap-1.5 pt-1">
            {#each tags as tag}
              <span class="inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full bg-indigo-500/10 text-indigo-600 dark:text-indigo-400 border border-indigo-500/20 text-[10px] font-bold">
                #{tag}
                <button type="button" onclick={() => removeTag(tag)} class="hover:text-rose-500">
                  <X class="w-2.5 h-2.5" />
                </button>
              </span>
            {/each}
          </div>
        </div>

      </form>

      <!-- Fixed Action Footer (shrink-0) -->
      <div class="px-6 py-3.5 border-t border-slate-200 dark:border-slate-800 bg-slate-50/80 dark:bg-[#070a13]/80 flex items-center justify-end gap-3 shrink-0">
        <button
          type="button"
          onclick={() => taskStore.closeModal()}
          class="px-4 py-2 text-xs font-semibold text-slate-600 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-100 transition-colors"
        >
          Cancel
        </button>
        <button
          type="submit"
          form="task-modal-form"
          class="flex items-center gap-1.5 px-4 py-2 text-xs font-bold rounded-xl text-white bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-500 hover:to-violet-500 shadow-md shadow-indigo-500/20 transition-all active:scale-95"
        >
          <Save class="w-3.5 h-3.5" />
          <span>{taskStore.editingTaskId ? 'Save Changes' : 'Create Task'}</span>
        </button>
      </div>

    </div>
  </div>
{/if}
